### ISSUE TITLE
Rename package product to MapLibre

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-gl-native-distribution#13]
https://github.com/maplibre/maplibre-gl-native-distribution/blob/d761956e81e74d8bdbfba31e0ec3a75616190658/Package.swift#L8

https://github.com/maplibre/maplibre-gl-native-distribution/blob/d761956e81e74d8bdbfba31e0ec3a75616190658/Package.swift#L9

Can this be renamed to MapLibre? It shows up like this right now:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/649392/210644382-abf7bf66-edf7-4a5d-992c-e40da507d140.png">

**Comment by roblabs** [comment]
It is possible, of course, to change the library name.  I have always leaned towards leaving it *as is*, with the rationale is that is originally the Mapbox SDK.  I will leave it to the MapLibre community to decide.

The library is used in Swift as `import Mapbox`.  It will be a breaking change that we'll need to communicate to consumers of the Swift Package if it is renamed.

**Comment by andyzaharia** [comment]
I'm also inclined to have the framework renamed. 

I think there might be use cases where one will use both SDKs in the same app.

**Comment by roblabs** [comment]
Can this be closed with https://github.com/maplibre/maplibre-gl-native-distribution/commit/71237cde41cad7b2af4df2abed637383e879fb2e#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677e?

**Comment by louwers** [comment]
Yes!

You also need to use `import MapLibre` from 6.0.0.
