### ISSUE TITLE
Can not use MGLCluster to show Marker Cluster

### ISSUE THREAD

**Issue by thothai94** [maplibre/maplibre-gl-native-distribution#17]
I used Mapbox's tutorial at https://docs.mapbox.com/ios/legacy/maps/examples/clustering/ to show Marker Cluster but mapView only show nonCluster point like picture below.
![image](https://user-images.githubusercontent.com/20405229/216496758-2401bed6-6c39-466b-9679-d08b22a45f21.png)
I'm using newest version 5.13.0
Please help me with this issue!

**Comment by louwers** [comment]
Please report this at https://github.com/maplibre/maplibre-native if you believe this is a bug, or create a Discussion there.

Thanks.
