### ISSUE TITLE
[Bug] Can't build 5.11.0 version

### ISSUE THREAD

**Issue by shinriyo** [maplibre/maplibre-gl-native-distribution#22]
I'd built SimpleMap_UIKit sample and set version more than 5.11.0 version.

<img width="867" alt="スクリーンショット 2023-08-30 16 17 39" src="https://github.com/maplibre/maplibre-gl-native-distribution/assets/396927/b4fe0956-503e-4809-b45b-e3e4e8f47236">

.xcodeproj Missing package product 'MapboxMobileEvents' happned.

**Comment by shinriyo** [comment]
<img width="1032" alt="スクリーンショット 2023-08-30 16 32 49" src="https://github.com/maplibre/maplibre-gl-native-distribution/assets/396927/1cbb307c-16cb-4ef9-8c33-1d2878bb57ce">
I set Mapbox, MapboxMobileEvents there.

 but no working

**Comment by shinriyo** [comment]
https://github.com/mapbox/mapbox-gl-native-ios/issues/131

**Comment by shinriyo** [comment]
I removed `https://github.com/maptiler/maplibre-gl-native-distribution.git` SPM
And add this repository's

maptiler is deprecated??


https://github.com/maptiler/maplibre-gl-native-distribution
↓
https://github.com/maplibre/maplibre-gl-native-distribution

Same??

**Comment by shinriyo** [comment]
I accessed maptiler's URL and redirected maplibre's one.

**Comment by shinriyo** [comment]
no replying.
is it out of service???

**Comment by louwers** [comment]
@shinriyo Sorry, missed your messages here. Please try with version 5.13.0.

As mentioned in the README, please use the [main repo of MapLibre Native](https://github.com/maplibre/maplibre-native) to ask for help.
