### ISSUE TITLE
MLNMapViewDelegate on 6.8.0 doesn't work - MOVED

### ISSUE THREAD

**Issue by seraph3b** [maplibre/maplibre-gl-native-distribution#27]
moved on maplibre repo

**Comment by cgalvan** [comment]
The issue this was moved to (https://github.com/maplibre/maplibre-native/issues/2993) has been closed. The issue with loading some map styles has been resolved in `6.8.1`, so I am closing this issue as well. Thank you for finding/reporting this issue!
