### ISSUE TITLE
AWS map failed to load with HTTP status code 403 on 6.8.0

### ISSUE THREAD

**Issue by animeshsen** [maplibre/maplibre-gl-native-distribution#28]
I was using AWS Map-style URL with the cognito auth method in iOS, but it stopped working after we updated Mablibre Native SDK to 6.8.0 in Swift Package Manager.

Getting below error: 
The map failed to load because the style can't be loaded." UserInfo={NSLocalizedDescription=The map failed to load because the style can't be loaded., NSLocalizedFailureReason=loading style failed: HTTP status code 403}

It started working again as soon as we downgraded SDK the version to 6.7.1

**Comment by cgalvan** [comment]
Hello @animeshsen , can you please supply the code you are using for your cognito authentication, as well as the style URL you are passing to MapLibre? Is there a full stack trace available or do you only see that error log in the console?

**Comment by animeshsen** [comment]
#

**Comment by animeshsen** [comment]
Hello @cgalvan, here is the details you requested.

MapStyle URL: https://maps.geo.ap-southeast-2.amazonaws.com/maps/v0/maps/maps-esri-dev/style-descriptor

```
private func setupMapView() {
        let region = (regionName as NSString).aws_regionTypeValue()
        signingDelegate = AWSSignatureV4Delegate(region: region, identityPoolId: identityPoolId)
        
        // register a delegate that will handle SigV4 signing
        MLNOfflineStorage.shared.delegate = signingDelegate
        
        let styleURL = URL(string: String(format: Constant.UI.MapView.mapStyleURL, regionName, mapName))
        
        self.mapView = MLNMapView(frame: UIScreen.main.bounds)
        self.mapView.styleURL = styleURL
        self.mapView.logoView.isHidden = true
        self.mapContainerView.addSubview(mapView)
        self.mapView.delegate = self
}
```

**Comment by cgalvan** [comment]
Hello @animeshsen, thanks for providing the details! We identified an issue in the `6.8.0` release that caused some map styles to not load properly. Please try out the new `6.8.1` release and let me know if this resolves your issue:

https://github.com/maplibre/maplibre-native/releases/tag/ios-v6.8.1

Thank you

**Comment by louwers** [comment]
Please let us know if you are still having problems with 6.8.1. Thanks.

**Comment by animeshsen** [comment]
Hello @cgalvan, It is working fine with version 6.8.1. Thanks.
