### ISSUE TITLE
dyld: Library not loaded: @rpath/Mapbox.framework/Mapbox

### ISSUE THREAD

**Issue by ferologics** [maplibre/maplibre-gl-native-distribution#4]
Hi, I'm getting an error after integrating the SPM package:
```
dyld: Library not loaded: @rpath/Mapbox.framework/Mapbox
  Referenced from: /private/var/containers/Bundle/Application/78B0CD80-E815-4338-9416-DFBBFC5C2C87/Connect.app/Frameworks/Map.framework/Map
  Reason: image not found
```

Perhaps it's an Xcode bug? https://developer.apple.com/forums/thread/652873

Edit: I'm using: 
- Xcode Version 12.4 (12D4e)
- macOS 11.3 Beta (20E5186d)

**Comment by ferologics** [comment]
I have tried to manually add the `LD_RUNPATH_SEARCH_PATH` with correct path to `@executable_path/Frameworks/MapDependencies.framework/Frameworks` 
![image](https://user-images.githubusercontent.com/5576161/112135246-e0bd7000-8bcd-11eb-85a4-fca1ca0dd1fc.png)
but even that does not seem to be the right way to go a about it:
```
code signature in (/private/var/containers/Bundle/Application/BA2D8688-3CAA-4A05-85C3-71C054415349/Connect.app/Frameworks/MapDependencies.framework/Frameworks/Mapbox.framework/Mapbox) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```
^ `code signature in ... not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed`

**Comment by ferologics** [comment]
Apparently there is a [workaround for the code signing issue](https://github.com/opencv/opencv/issues/15645#issuecomment-557790394) but our app does not make use of hardened runtime.

**Comment by ferologics** [comment]
Here's a few related threads pointing more fingers at Apple and iffy SPM Xcode integration for binary targets:
- https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953
- https://developer.apple.com/forums/thread/662247
- https://github.com/zocario/swiftpm_archive_binary_target

Adding `--deep` to the `OTHER_CODE_SIGN_FLAGS` build setting did not resolve my issue.

**Comment by ferologics** [comment]
The [workaround is to add two new build phases](https://pspdfkit.com/guides/ios/knowledge-base/library-not-found-swiftpm/):
1. copy files build phase (frameworks)
2. run script phase that forces deep signing

**Comment by ferologics** [comment]
Closing as this doesn't seem to be happening with latest Xcode

**Comment by EvgenijLutz** [comment]
Looks like it's happening again. I added the package via SPM. It runs on Simulator, but not on a real device. The error is the same as above:
```
dyld[1844]: Library not loaded: @rpath/Mapbox.framework/Mapbox
  Referenced from: /private/var/containers/Bundle/Application/1DC0E379-22BC-4F00-9546-BA181537D315/maptest.app/maptest
  Reason: tried: '/usr/lib/swift/Mapbox.framework/Mapbox' (no such file), '/usr/lib/swift/Mapbox.framework/Mapbox' (no such file), '/System/Library/Frameworks/Mapbox.framework/Mapbox' (no such file)
```

**Comment by roblabs** [comment]
Please see https://github.com/maplibre/maplibre-gl-native/issues/49 which documents, tests & demonstrates MapLibre GL Native running on iOS (and Android) devices.  Also included are notes on using the Swift Package Manager.  There are detailed steps that may be of use for your `maptest.app`.

You can also review:

* The releases page on this repo which notes best practices for Swift Package Manager —  https://github.com/maplibre/maplibre-gl-native-distribution/releases
* A Repo with a sample iOS app that demonstrates & deploys to devices using three different SDKs:   MapLibre GL, MapLibre with *Metal Support*, and Mapbox v10 — https://github.com/roblabs/openmaptiles-ios-demo/branches
