### ISSUE TITLE
Running MapLibre Open GL project on Apple Silicon device has better Simulator performance on `x86_64` than `arm64`.

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-gl-native-distribution#7]
The MapLibre project [provides iOS binaries](https://github.com/maplibre/maplibre-gl-native-distribution/releases) for both `x86_64` & `arm64` which allows for Simulator development on either Intel or Apple Silicon architectures.

When using the `Mapbox.xcframework` for a 3rd party map project, there are several issues when targeting the iOS Simulator for `arm64`.

---

**Issues**

1. MapLibre targeting `arm64` iOS Simulators 14.5 & 16.0 have a drawing error that is eventually fixed when the map is at steady state.
2. MapLibre targeting `arm64` iOS Simulators 15.4 & 15.5 have a drawing error, followed by an exception when moving the map.
3. MapLibre targeting `x86_64` iOS Simulators fixes drawing & exception issues for SDKs 14.5, 15.4, 15.5, & 16.0.

---

**Questions**

* Why does setting [`EXCLUDED_ARCHS`](https://developer.apple.com/documentation/Xcode/build-settings-reference#Excluded-Architectures), and force targeting `x86_64` seem to be the accepted workaround for Simulators on Apple Silicon?
  * `EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64`
* What changed from iOS Simulator 14.5 to 15.5 and to 16.0?
  * Why so many log warnings for `'cyclone' is not a recognized processor for this target (ignoring processor)`?  These are fixed when targeting `x86_64`.

**Test environment**

* macOS Ventura 13.0 Beta (22A5295i).  Occurs on Big Sur on M1 Apple Silicon, too.
* Xcode Version 14.0 beta 3 (14A5270f).  Occurs with Xcode 13.4, too.
  * Xcode Version 14.0 beta 4 (14A5284g).
* M1 Apple Silicon
* No issue when running on iOS Devices
---

| Simulator SDK version    | Target Architecture   | Notes |
| :------------- | :------------- | :---:
| 14.5       |  `arm64`      | a. Issue type 1) Missing a polygon for a solid area that eventually is drawn.  <img width="50%" src="https://user-images.githubusercontent.com/118112/179640578-51bdbc68-9735-4b08-9c36-2638775f734b.png">  <br> b. Log contains `'cyclone' is not a recognized processor for this target (ignoring processor)`
| 15.4       |  `arm64`      | a. Issue type 2) Poorly drawn initial frame, then exception after moving map. `EXC_BAD_ACCESS (code =2, address)`.  <img width="50%" src="https://user-images.githubusercontent.com/118112/179640612-3b394513-94ef-4a5d-949e-8ce4a31d44fa.png"> <br> b. Log contains `'cyclone' is not a recognized processor for this target (ignoring processor)`
| 15.5       |  `arm64`      | a. Issue type 2) Exception right away.  `EXC_BAD_ACCESS (code =2, address)`
| 16.0 (beta 3)       |  `arm64`      | a. Issue type 1)  Missing a polygon for a solid area that eventually is drawn.  <img width="50%" src="https://user-images.githubusercontent.com/118112/179640626-c0ef97d9-4172-466b-99e9-2adad9ec9bd1.png"> <br> b. Log contains `'cyclone' is not a recognized processor for this target (ignoring processor)`
| 14.5       |  `x86_64` | No visible issues after `EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64`
| 15.4       |  `x86_64` | "
| 15.5       |  `x86_64` | "
| 16.0       |  `x86_64` | "

---

# Test Results

## Test iOS Simulator targeting `arm64`

Four iOS Simulators:

### ↙️ 15.5 — 16.0 ↘️ (Xcode 14.0 beta 3 (14A5270f))

https://user-images.githubusercontent.com/118112/179642179-d0f2f20e-ea19-4bec-8e84-ecc0892173ec.mov

---

## Test iOS Simulator targeting `x86_64`

Four iOS Simulators:

### ↙️ 15.5 — 16.0 ↘️ (Xcode 14.0 beta 3 (14A5270f))

https://user-images.githubusercontent.com/118112/179642155-13e689a0-0571-4cbb-b515-ed75aaf83997.mov

---

### `Mapbox.xcframework` *lipo* information

```bash
# lipo -info Mapbox.xcframework/ios-arm64_armv7/Mapbox.framework/Mapbox
Architectures in the fat file: Mapbox.xcframework/ios-arm64_armv7/Mapbox.framework/Mapbox are: armv7 arm64


# lipo -info Mapbox.xcframework/ios-arm64_i386_x86_64-simulator/Mapbox.framework/Mapbox
Architectures in the fat file: Mapbox.xcframework/ios-arm64_i386_x86_64-simulator/Mapbox.framework/Mapbox are: x86_64 i386 arm64
```

---

*`Mapbox.xcframework` for devices & simulators.*

![](https://user-images.githubusercontent.com/118112/179640649-34e29a2d-1f82-4f5e-902a-1659ba2281d4.png)

---

`arm64` Simulator throws many not recognized processors.

> 'cyclone' is not a recognized processor for this target (ignoring processor)
'cyclone' is not a recognized processor for this target (ignoring processor)
<snip>
'cyclone' is not a recognized processor for this target (ignoring processor)

---

**Comment by roblabs** [comment]
The issue of "_intermittent missing polygons in iOS 16_" still exists with Xcode Version 14.0 beta 4 (14A5284g).

The same test conditions were applied:  using the MapLibre distributed binaries via Swift Package on a 3rd party map project, tested on Apple Silicon.

**Comment by roblabs** [comment]
Issue still exists under the same test conditions with Xcode Version 14.0 beta 5 (14A5294e) which was released on Aug 8, 2022.

* targeting `arm64` iOS Simulator 16.0 has a drawing error (the missing polygon issue) that is eventually fixed when the map is at steady state.
* targeting `arm64` iOS Simulator 15.5 has an exception

**Comment by roblabs** [comment]
Issue still exists under the same test conditions with Xcode Version 14.0 beta 6 (14A5294g) which was released on Aug 23, 2022.  The test with Xcode Beta 6 was ran on macOS 13 beta 6 (22A5331f).

* targeting `arm64` iOS Simulator 16.0 has a drawing error (the missing polygon issue) that is eventually fixed when the map is at steady state.
* targeting `arm64` iOS Simulator 15.5 has an exception

**Comment by roblabs** [comment]
Issue still exists under the same test conditions with Xcode Version 14.0 RC (14A309) which was released on Sep 7, 2022.

* targeting `arm64` iOS Simulator 16.0 has a drawing error (the missing polygon issue) that is eventually fixed when the map is at steady state.
* targeting `arm64` iOS Simulator 15.5 has an exception.

**Comment by birkskyum** [comment]
Is it resolved with the final xcode 14?

**Comment by louwers** [comment]
Closing this. With Metal support running MapLibre Native in the simulator works much better.
